name: Feature Request
description: Suggest a new feature for the school activities system
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for improving our school activities system? Tell us about it!
        
  - type: textarea
    id: feature-description
    attributes:
      label: What new feature would you like to see?
      description: Describe the new functionality you're requesting
      placeholder: e.g., Email notifications when activities are updated, calendar view of activities, ability to add students to waitlist
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: What problem would this feature solve?
      description: Explain why this feature is needed and what current problem it addresses
      placeholder: e.g., Students miss registration deadlines, teachers can't track attendance, hard to see schedule conflicts
    validations:
      required: true

  - type: checkboxes
    id: user-type
    attributes:
      label: Who would use this feature?
      options:
        - label: Students
        - label: Teachers
        - label: School administrators
        - label: Parents
        - label: Other (specify below)

  - type: textarea
    id: how-it-works
    attributes:
      label: How should this feature work?
      description: Describe step-by-step how users would interact with this new feature
      placeholder: |
        1. User goes to...
        2. User clicks on...
        3. System displays...
        4. User can then...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: What type of feature is this?
      options:
        - Communication/Notifications
        - Reporting and Analytics
        - User Management
        - Scheduling and Calendar
        - Search and Discovery
        - Data Export/Import
        - Security and Access Control
        - Mobile App Features
        - Integration with Other Systems
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature?
      options:
        - Critical (system is difficult to use without it)
        - High (would significantly improve user experience)
        - Medium (nice to have, would make things easier)
        - Low (minor convenience enhancement)
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples or Similar Features
      description: Are there other websites or systems that have similar features you like?
      placeholder: e.g., "Like how Gmail shows notifications" or "Similar to the calendar view in Google Calendar"

  - type: textarea
    id: alternatives
    attributes:
      label: Current Workarounds
      description: How do users currently handle this without the feature? What's the current process?
      placeholder: e.g., Teachers manually email students, Students check website daily, Paper sign-up sheets

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Suggestions
      description: Do you have ideas about how this could be built or integrated?
      placeholder: e.g., Add new page to website, Send automatic emails, Add button to existing page, Mobile app feature

  - type: textarea
    id: success-metrics
    attributes:
      label: How would we measure success?
      description: How would we know this feature is working well and being used effectively?
      placeholder: e.g., Increased student registrations, Fewer missed deadlines, Teachers report time savings, Positive user feedback

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Feature Requirements
      description: What must be true when this feature is successfully implemented?
      options:
        - label: Feature is easy to find and use for intended users
          required: true
        - label: Feature works on both desktop and mobile devices
          required: true
        - label: Feature doesn't break existing functionality
          required: true
        - label: Feature includes appropriate error handling and user feedback
          required: true
        - label: Feature is documented for users who need to learn how to use it
          required: true
        - label: Feature meets school's security and privacy requirements
          required: true